// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\crud\ControllerImpl.java.vsl) on 04/16/2011 23:05:14+0200
package org.andromda.test.howto16.a.crud;

import java.io.Serializable;

/**
 * @see org.andromda.test.howto16.a.crud.CarController
 */
public class CarControllerImpl extends CarController implements Serializable
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 8981610972593002909L;

}
