// license-header java merge-point
//
// Generated by: SessionBeanImpl.vsl in andromda-ejb3-cartridge.
//
package org.andromda.test.howto10.a;

/**
 * @see PaymentServiceBase
 * Remember to manually configure the local business interface this bean implements if originally you only
 * defined the remote business interface. However, this change is automatically reflected in the ejb-jar.xml.
 * Do not specify the javax.ejb.Stateless annotation
 * Instead, the session bean is defined in the ejb-jar.xml descriptor.
 */
// Uncomment to enable webservices for PaymentServiceBean
// @javax.jws.WebService(endpointInterface = "org.andromda.test.howto10.a.PaymentServiceWSInterface", serviceName = "PaymentService")
public class PaymentServiceBean extends PaymentServiceBase implements PaymentServiceRemote
{

    // --------------- Constructors ---------------

    /**
     * Default constructor extending base class default constructor
     */
    public PaymentServiceBean()
    {
        super();
    }

    // -------- Business Methods Impl --------------

    /**
     * @see PaymentServiceBase#register(Person, Car, int)
     */
    protected void handleRegister(Person owner, Car car, int leasePeriod) throws Exception
    {
        // TODO: put your implementation here.
        throw new UnsupportedOperationException("org.andromda.test.howto10.a.PaymentServiceBean.handleRegister(Person owner, Car car, int leasePeriod) Not implemented!");
    }

    // -------- Lifecycle Callback Implementation --------------

}
